name: deploy with ovh
on: [push]

env:
    DEBUG: ${{secrets.DEBUG}}
    OVH_IP_ADDRESS: ${{secrets.OVH_IP_ADDRESS}}
    OVH_USER: ${{secrets.OVH_USER}}
    OVH_PRIVATE_KEY: ${{secrets.OVH_PRIVATE_KEY}}
jobs:
    run_tests:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Run script file
              run: |
                  chmod +x ./apps/setup_env.sh
                  bash ./apps/setup_env.sh
            - run: cat ./apps/.env
