name: deploy with ovh
on: [push]

jobs:
    run_tests:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Run script file
              run: |
                  chmod +x ./apps/setup_env.sh
                  bash ./apps/setup_env.sh
            - run: cat ./.env 
